# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insert_sdf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='insert_sdf.proto',
  package='tol.msgs',
  serialized_pb='\n\x10insert_sdf.proto\x12\x08tol.msgs\":\n\x10InsertSdfRequest\x12\x10\n\x08robot_id\x18\x01 \x02(\t\x12\x14\n\x0csdf_contents\x18\x02 \x02(\t\"6\n\x11InsertSdfResponse\x12\x10\n\x08robot_id\x18\x01 \x02(\t\x12\x0f\n\x07success\x18\x02 \x02(\x08')




_INSERTSDFREQUEST = _descriptor.Descriptor(
  name='InsertSdfRequest',
  full_name='tol.msgs.InsertSdfRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='tol.msgs.InsertSdfRequest.robot_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdf_contents', full_name='tol.msgs.InsertSdfRequest.sdf_contents', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=88,
)


_INSERTSDFRESPONSE = _descriptor.Descriptor(
  name='InsertSdfResponse',
  full_name='tol.msgs.InsertSdfResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='tol.msgs.InsertSdfResponse.robot_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='tol.msgs.InsertSdfResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=90,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['InsertSdfRequest'] = _INSERTSDFREQUEST
DESCRIPTOR.message_types_by_name['InsertSdfResponse'] = _INSERTSDFRESPONSE

class InsertSdfRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSERTSDFREQUEST

  # @@protoc_insertion_point(class_scope:tol.msgs.InsertSdfRequest)

class InsertSdfResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSERTSDFRESPONSE

  # @@protoc_insertion_point(class_scope:tol.msgs.InsertSdfResponse)


# @@protoc_insertion_point(module_scope)
