#ifndef TESTYAMLBODYPARSER_H
#define TESTYAMLBODYPARSER_H

#include <string>

namespace tol {

static const std::string Spider9_yaml_source =
        "---\n"
        "body:\n"
        "  id          : Core\n"
        "  type        : Core\n"
        "  children    :\n"
        "    0:\n"
        "      id          : Leg00Joint\n"
        "      type        : ActiveHinge\n"
        "      orientation : 90\n"
        "      children    :\n"
        "        1:\n"
        "          id          : Leg00\n"
        "          type        : FixedBrick\n"
        "          orientation : -90\n"
        "          children    :\n"
        "            1:\n"
        "              id          : Leg01Joint\n"
        "              type        : ActiveHinge\n"
        "              children    :\n"
        "                1:\n"
        "                  id          : Leg01\n"
        "                  type        : FixedBrick\n"
        "                  orientation : 0\n"
        "    1:\n"
        "      id          : Leg10Joint\n"
        "      type        : ActiveHinge\n"
        "      orientation : 90\n"
        "      children    :\n"
        "        1:\n"
        "          id          : Leg10\n"
        "          type        : FixedBrick\n"
        "          orientation : -90\n"
        "          children    :\n"
        "            1:\n"
        "              id          : Leg11Joint\n"
        "              type        : ActiveHinge\n"
        "              children    :\n"
        "                1:\n"
        "                  id          : Leg11\n"
        "                  type        : FixedBrick\n"
        "                  orientation : 0\n"
        "    2:\n"
        "      id          : Leg20Joint\n"
        "      type        : ActiveHinge\n"
        "      orientation : 90\n"
        "      children    :\n"
        "        1:\n"
        "          id          : Leg20\n"
        "          type        : FixedBrick\n"
        "          orientation : -90\n"
        "          children    :\n"
        "            1:\n"
        "              id          : Leg21Joint\n"
        "              type        : ActiveHinge\n"
        "              children    :\n"
        "                1:\n"
        "                  id          : Leg21\n"
        "                  type        : FixedBrick\n"
        "                  orientation : 0\n"
        "    3:\n"
        "      id          : Leg30Joint\n"
        "      type        : ActiveHinge\n"
        "      orientation : 90\n"
        "      children    :\n"
        "        1:\n"
        "          id          : Leg30\n"
        "          type        : FixedBrick\n"
        "          orientation : -90\n"
        "          children    :\n"
        "            1:\n"
        "              id          : Leg31Joint\n"
        "              type        : ActiveHinge\n"
        "              children    :\n"
        "                1:\n"
        "                  id          : Leg31\n"
        "                  type        : FixedBrick\n"
        "                  orientation : 0";

}

#endif // TESTYAMLBODYPARSER_H
