#!/bin/bash
# Runs gazebo with the correct plugin path
if [ "$1" == "--visual" ]; then
    CMD=gazebo
else
    CMD=gzserver
fi
GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:`pwd`/../build GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:`pwd`/models $CMD -u demo.world
