#!/bin/bash
# Runs gazebo with the correct plugin path
WORLD=demo.world
if [ "$1" == "--visual" ]; then
    CMD=gazebo
else
    CMD=gzserver
fi

if [ "$1" == "--interactive" ]; then
    CMD=gazebo
    WORLD=idemo.world
fi

GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:`pwd`/../build GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:`pwd`/models $CMD -u $WORLD
